- name: "Provision Docker Swarm Cluster"
  hosts: all
  roles:
    - { role: atosatto.docker-swarm }
  tasks:
    - name: "install docker-compose-swarm-mode"
      pip: name=docker-compose-swarm-mode version=1.1.1 state=present
