---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Install the Docker Engine
- include: docker_engine.yml

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
